spring:
  application:
    name: client-sample
client:
  max-connections: 100
  pending-acquire-timeout: 60
  connection-timeout: 10000
  read-timeout: 10
  write-timeout: 10
  weather:
    scheme: https
    host: api.open-meteo.com